# Generated by Django 3.2 on 2024-09-26 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astralprojapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(blank=True, max_length=200, null=True)),
                ('current_location', models.CharField(blank=True, max_length=20, null=True)),
                ('destination', models.CharField(blank=True, max_length=20, null=True)),
                ('package_info', models.CharField(blank=True, max_length=500, null=True)),
                ('total_weight', models.IntegerField(blank=True, default=0, null=True)),
                ('description', models.CharField(blank=True, default='color, weight, name, type of goods', max_length=500, null=True)),
                ('image_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='astralprojapp.client')),
            ],
        ),
    ]
