# Generated by Django 3.2 on 2024-09-27 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astralprojapp', '0002_tracking_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking_info',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
